export const plantsObj = {
  plants: [
    {
      category: "Хвойные деревья",
      name: "Сосна обыкновенная (Pinus sylvestris)",
      h: "20.0 - 25.0 m",
      d: "8.0 - 10.0 m",
      winterResistance: "высокая",
      location: ["солнце"],
      grounds: [
        "воздухопроницаемые",
        "супесчаные",
        "легкие",
        "умеренно увлажненные",
      ],
      specialAspects: "ветро- и газоустойчивость. Не переносит застоя влаги",
      imageUrl: "sosna",
    },
    {
      category: "Хвойные кустарники",
      name: 'Можжевельник казацкий "Рокери Джем" / Juniperus Sabina "Rockery Gem"',
      h: "0.4 - 0.5 m",
      d: "1.2 - 1.6 m",
      winterResistance: "высокая",
      location: ["солнце"],
      grounds: [
        "воздухопроницаемые",
        "супесчаные",
        "легкие",
        "умеренно увлажненные",
      ],
      specialAspects:
        "ветро- и газоустойчивость. Не переносит застоя влаги. Хорошо переносит стрижку.",
      imageUrl: "juniper",
    },
    {
      category: "Лиственные деревья",
      name: "Рябина сибирская (Sorbus sibirica)",
      h: "8.0 - 10.0 m",
      d: "7.0 - 8.0 m",
      winterResistance: "высокая",
      location: ["солнце", "полутень"],
      grounds: ["воздухопроницаемые", "питательные", "легкие", "увлажненные"],
      specialAspects: "ветро- и газоустойчивость",
      imageUrl: "rowan",
    },
    {
      category: "Лиственные деревья",
      name: "Черемуха виргинская (Prunus virginiana)",
      h: "6.0 - 7.0 m",
      d: "4.0 - 5.0 m",
      winterResistance: "высокая",
      location: ["солнце", "полутень"],
      grounds: ["воздухопроницаемые", "питательные", "легкие", "увлажненные"],
      specialAspects: "ветро- и газоустойчивость. Хорошо переносит стрижку.",
      imageUrl: "bird_cherry",
    },
    {
      category: "Лиственные кустарники",
      name: "Гортензия метельчатая (Hydragea paniculata `Skyfall`)",
      h: "1.0 - 2.0 m",
      d: "0.9 - 1.0 m",
      winterResistance: "высокая",
      location: ["солнце", "полутень"],
      grounds: ["воздухопроницаемые", "легкие", "увлажненные"],
      specialAspects: "мульчирование, защита от ветра",
      imageUrl: "hydrangea",
    },
    {
      category: "Лиственные кустарники",
      name: "Стефанандра недрезаннолистная (Stephanandra incise)",
      h: "1.0 - 1.2 m",
      d: "1.2 - 1.5 m",
      winterResistance: "высокая",
      location: ["солнце", "полутень"],
      grounds: ["воздухопроницаемые", "питательные", "увлажненные"],
      specialAspects: "может подмерзать до снеговой линии",
      imageUrl: "stefandra",
    },
    {
      category: "Лиственные кустарники",
      name: "Спирея японская (`Spirea japonica 'Golden Princess')",
      h: "0.4 - 0.5 m",
      d: "0.4 - 0.5 m",
      winterResistance: "высокая",
      location: ["солнце", "полутень"],
      grounds: ["рыхлые", "питательные", "увлажненные"],
      specialAspects:
        "устойчивая к условиям города, переносит кратковременную засуху и застой влаги, необходима обрезка",
      imageUrl: "spirea",
    },
    {
      category: "Лианы",
      name: "Девичий виноград (Parthenocissus)",
      h: "10.0 - 15.0 m",
      d: "1.2 - 1.5 m",
      winterResistance: "высокая",
      location: ["солнце", "полутень"],
      grounds: ["рыхлые", "питательные", "увлажненные"],
      specialAspects: "для эстетичного развития необходимо формирование лианы",
      imageUrl: "grace",
    },
    {
      category: "Травянистые многолетники",
      name: "Дербенник иволистный (Lythrum salicaria)",
      h: "1.0 - 1.3 m",
      d: "0.4 - 0.5 m",
      winterResistance: "высокая",
      location: ["солнце", "полутень"],
      grounds: ["рыхлые", "питательные", "увлажненные до болотистой"],
      specialAspects: "рекомендуется обрезка после цветения",
      imageUrl: "derbenik",
    },
    {
      category: "Травянистые многолетники",
      name: "Седум видный `Brilliant` (Sedum spectabile `Brilliant`)",
      h: "0.3 - 0.4 m",
      d: "0.2 - 0.3 m",
      winterResistance: "высокая",
      location: ["солнце"],
      grounds: ["рыхлые", "питательные", "супесчаные"],
      specialAspects: "не переносит переувлажнения",
      imageUrl: "sedum",
    },
  ],
};
